### ISSUE TITLE
install.sh script is missing

### ISSUE THREAD

**Issue by fkromer** [camfowler/vim#2]
The install.sh script from [your post in medium](https://stories.abletech.nz/get-rid-of-your-vim-plugin-manager-7c8ff742f643) is the one mentioned in the README I guess?

**Comment by marmalodak** [comment]
Have a look at [this commit](https://github.com/camfowler/vim/commit/290619b10ab808cf1a71e8d1ced014b79b703d5d).

tl;dr [camfowler](https://github.com/camfowler) now uses [git submodules.](https://git-scm.com/docs/git-submodule)

If that answers your question, consider closing this issue.

**Comment by fkromer** [comment]
Thx
